swagger: '2.0'
# This is your document metadata
info:
  version: "0.0.0"
  title: Example API resources documentation
schemes:
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
tags:
  - name: Building
    description: Building resources
  - name: Rubric
    description: Rubric resources
  - name: Company
    description: Company resources

# will be prefixed to all paths
basePath: /api/
paths:
  /building/:
    get:
      tags:
        - Building
      description: Retrieve a building list
      responses:
        200:
          description: Retrieve a building list
          schema:
            type: array
            items:
              $ref: '#/definitions/Building'
  # Rubric
  /rubric/rubricator/:
    get:
      tags:
       - Rubric
      description: Retrieve rubric tree
      responses:
        200:
          description: Retrieve rubric tree
          schema:
            $ref: '#/definitions/Rubric'
  /rubric/rubricator/{rubricId}/:
    get:
      tags:
       - Rubric
      parameters:
        - in: path
          name: rubricId
          required: True
          type: integer
      description: Retrieve rubric tree by specified parent
      responses:
        200:
          description: Retrieve rubric tree by specified parent
          schema:
            $ref: '#/definitions/Rubric'
  # Company
  /company/:
    get:
      tags:
        - Company
      parameters:
        - in: path
          name: building
          required: false
          type: integer
          description: filter by buildingId
        - in: path
          required: false
          name: name
          type: string
          description: search by name
        - in: path
          required: false
          name: rubric
          type: integer
          description: filter by rubricId
      description: Retrieve company list filtered by specified parameters
      responses:
        200:
          description: Company list filtered by specified parameters
          schema:
            type: array
            title: List of companies
            items:
              $ref: '#/definitions/CompanyList'
  /company/{companyId}/:
    get:
      tags:
        - Company
      parameters:
        - in: path
          name: companyId
          required: true
          type: integer
          description: 
      description: Retrieve specified company
      responses:
        200:
          description: Retrieve specified company
          schema:
            $ref: '#/definitions/CompanyList'

definitions:

  # Responses
  SerializerError:
    type: array
    items:
      title: SerializerError
      type: object
      properties:
        fieldname:
          type: string
        errormessage:
          type: string
  ResultObject:
    type: array
    title: Result
    items:
      type: object
      properties:
        result:
          type: boolean
        message:
          type: string
  PermissionDenied:
    type: object
    properties:
      detail:
        type: string
  # Models
  Building:
    type: object
    title: Building
    properties:
      id:
        type: integer
      address:
        type: string
      lat:
        type: integer
      lon:
        type: string

  CompanyList:
    type: object
    title: CompanyList
    properties:
      id:
        type: integer
      name:
        type: string
      building:
        $ref: '#/definitions/Building'
      phones:
        type: array
        items:
          type: string
      rubrics:
        type: array
        items:
          type: string
  Rubric:
    type: object
    title: Rubric
    properties:
      id:
        type: integer
      name:
        type: string
      parent:
        $ref: '#/definitions/RubricParent'
  RubricParent:
    type: object
    title: RubricParent
    properties:
      id:
        type: integer
      name:
        type: string
