# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20151126_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='status',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='address'),
        ),
    ]
